version: '3.8'

services:
  vue_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/django_authenticated  # Mount the current directory to the /app directory in the container
